# Generated by Django 6.0.5 on 2026-06-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ResidentVerification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('PENDING', 'Pending'), ('VERIFIED', 'Verified'), ('REJECTED', 'Rejected')], default='PENDING', max_length=20)),
                ('valid_id_path', models.CharField(blank=True, max_length=500, null=True)),
                ('proof_of_residency_path', models.CharField(blank=True, max_length=500, null=True)),
                ('selfie_path', models.CharField(blank=True, max_length=500, null=True)),
                ('reviewed_at', models.DateTimeField(blank=True, null=True)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('reviewed_by', models.ForeignKey(blank=True, db_column='reviewed_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reviewed_verifications', to='accounts.user')),
                ('user', models.ForeignKey(db_column='user_id', on_delete=django.db.models.deletion.CASCADE, related_name='verifications', to='accounts.user')),
            ],
            options={
                'db_table': 'resident_verifications',
                'ordering': ['-created_at'],
            },
        ),
    ]
