# Generated by Django 6.0.5 on 2026-06-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='TanodDeployment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('zone_label', models.CharField(blank=True, max_length=255, null=True)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('availability_status', models.CharField(choices=[('AVAILABLE', 'Available'), ('RESPONDING', 'Responding'), ('ON_BREAK', 'On Break'), ('OFF_DUTY', 'Off Duty')], default='AVAILABLE', max_length=20)),
                ('shift_start', models.DateTimeField()),
                ('shift_end', models.DateTimeField(blank=True, null=True)),
                ('last_ping_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('tanod', models.ForeignKey(db_column='tanod_id', on_delete=django.db.models.deletion.CASCADE, related_name='deployments', to='accounts.user')),
            ],
            options={
                'db_table': 'tanod_deployments',
            },
        ),
    ]
