# Generated by Django 6.0.5 on 2026-06-04 15:52

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Incident',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('incident_number', models.CharField(max_length=50, unique=True)),
                ('incident_type', models.CharField(choices=[('PHYSICAL_ALTERCATION', 'Physical Altercation'), ('THEFT', 'Theft'), ('VANDALISM', 'Vandalism'), ('DOMESTIC_DISTURBANCE', 'Domestic Disturbance'), ('SUSPICIOUS_ACTIVITY', 'Suspicious Activity'), ('NOISE_COMPLAINT', 'Noise Complaint'), ('OTHER', 'Other')], default='OTHER', max_length=50)),
                ('priority', models.CharField(choices=[('LOW', 'Low'), ('MEDIUM', 'Medium'), ('HIGH', 'High'), ('CRITICAL', 'Critical')], default='LOW', max_length=20)),
                ('latitude', models.DecimalField(decimal_places=8, max_digits=10)),
                ('longitude', models.DecimalField(decimal_places=8, max_digits=11)),
                ('location_source', models.CharField(choices=[('GPS', 'GPS'), ('MANUAL', 'Manual')], default='GPS', max_length=10)),
                ('resolved_address', models.TextField(blank=True, null=True)),
                ('status', models.CharField(choices=[('REPORTED', 'Reported'), ('ASSIGNED', 'Assigned'), ('RESPONDING', 'Responding'), ('ON_SCENE', 'On Scene'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated'), ('REFERRED_TO_POLICE', 'Referred to Police'), ('UNABLE_TO_VERIFY', 'Unable to Verify')], default='REPORTED', max_length=30)),
                ('ai_summary', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('reported_by', models.ForeignKey(blank=True, db_column='reported_by', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='reported_incidents', to='accounts.user')),
            ],
            options={
                'db_table': 'incidents',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='IncidentAssignment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('assignment_role', models.CharField(choices=[('PRIMARY', 'Primary'), ('BACKUP', 'Backup'), ('REINFORCEMENT', 'Reinforcement')], default='PRIMARY', max_length=20)),
                ('assigned_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='incidents.incident')),
                ('tanod', models.ForeignKey(db_column='tanod_id', on_delete=django.db.models.deletion.CASCADE, related_name='assignments', to='accounts.user')),
            ],
            options={
                'db_table': 'incident_assignments',
            },
        ),
        migrations.CreateModel(
            name='IncidentAutoNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('distance_meters', models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True)),
                ('tanod_latitude', models.DecimalField(blank=True, decimal_places=8, max_digits=10, null=True)),
                ('tanod_longitude', models.DecimalField(blank=True, decimal_places=8, max_digits=11, null=True)),
                ('acknowledged', models.BooleanField(default=False)),
                ('acknowledged_at', models.DateTimeField(blank=True, null=True)),
                ('notified_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='auto_notifications', to='incidents.incident')),
                ('tanod', models.ForeignKey(db_column='tanod_id', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'incident_auto_notifications',
            },
        ),
        migrations.CreateModel(
            name='IncidentParticipant',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('unregistered_full_name', models.CharField(blank=True, max_length=255, null=True)),
                ('role', models.CharField(choices=[('REPORTER', 'Reporter'), ('VICTIM', 'Victim'), ('RESPONDENT', 'Respondent'), ('WITNESS', 'Witness')], max_length=20)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='participants', to='incidents.incident')),
                ('user', models.ForeignKey(blank=True, db_column='user_id', null=True, on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'incident_participants',
            },
        ),
        migrations.CreateModel(
            name='IncidentReport',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField()),
                ('image_path', models.CharField(blank=True, max_length=500, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='reports', to='incidents.incident')),
                ('reported_by', models.ForeignKey(db_column='reported_by', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'incident_reports',
            },
        ),
        migrations.CreateModel(
            name='IncidentStatusLog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_status', models.CharField(blank=True, choices=[('REPORTED', 'Reported'), ('ASSIGNED', 'Assigned'), ('RESPONDING', 'Responding'), ('ON_SCENE', 'On Scene'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated'), ('REFERRED_TO_POLICE', 'Referred to Police'), ('UNABLE_TO_VERIFY', 'Unable to Verify')], max_length=30, null=True)),
                ('new_status', models.CharField(choices=[('REPORTED', 'Reported'), ('ASSIGNED', 'Assigned'), ('RESPONDING', 'Responding'), ('ON_SCENE', 'On Scene'), ('RESOLVED', 'Resolved'), ('CLOSED', 'Closed'), ('ESCALATED', 'Escalated'), ('REFERRED_TO_POLICE', 'Referred to Police'), ('UNABLE_TO_VERIFY', 'Unable to Verify')], max_length=30)),
                ('remarks', models.TextField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('incident', models.ForeignKey(db_column='incident_id', on_delete=django.db.models.deletion.CASCADE, related_name='status_logs', to='incidents.incident')),
                ('updated_by', models.ForeignKey(db_column='updated_by', on_delete=django.db.models.deletion.CASCADE, to='accounts.user')),
            ],
            options={
                'db_table': 'incident_status_logs',
            },
        ),
    ]
